typeof() instead of type(): avoid clash with database field(?) "type"
Fixes this traceback:

Traceback (most recent call last):
  File "roundup\cgi_client.py", line 535, in newnode
    self._post_editnode(nid)
  File "roundup\cgi_client.py", line 415, in _post_editnode
    if type(value) != type([]): value = [value]
UnboundLocalError: local variable 'type' referenced before assignment