fix Class.get(): it was relying on self._marker...
...and that value was different for FileClass instances.
the _marker is moved to module globals.

fixes error in test testImportExport:
 TypeError: new property "comment" not a string: []