Fix issue2550843 (AttributeError: 'Unauthorised' object has no attribute 'replace')
Pass text of Unauthorised and Login exceptions instead of the exception
instance to avoid traceback with string operations.

str() is used in most other places where the exception error message text is
needed. So far only roundup.cgi.actions.LoginAction.handle() iterates over the
exception args. Probably not needed here, so I decided to keep the code simple.